# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90efbfadfdb45da2a75580f2e31b4a673e391c6199f86d7308f8441c44a040abb10c55b40feec7662b04ee70bdff0c4dd80c580432410ddd57a89d974bb716ba

test:
  secret_key_base: d9cbeee46cd7eca997cc1243b031ca99f847c8b4e0965ff26dde02942af31c5fa33975e7b9aec24a59036cc1588da0c465f5f5227126e1cda6721a8aaf651a6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
